# Generated by Django 4.2.4 on 2023-08-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_ttile",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
